define(["require"],function(){var module=(function(dependencies){return function(init){return init.call({},(function(){var moduleUrl=dependencies[0]["toUrl"]("todos.storage.js");var baseUrl=moduleUrl.substr(0,moduleUrl.lastIndexOf("/"));return{getSpaghettiVersion:function(){return "2.0";},getModuleName:function(){return "todos.storage";},getModuleVersion:function(){return "unspecified";},getResourceUrl:function(resource){if(resource.substr(0,1)!="/"){resource="/"+resource;}return baseUrl+resource;},"dependencies":{"require":dependencies[0]}};})());};})(arguments);return{"module":(function(){return module(function(Spaghetti) {
/// <reference path='../_all.ts' />
/// <reference path='../_all.ts' />
var todos;
(function (_todos) {
    var storage;
    (function (storage) {
        'use strict';
        /**
         * Services that persists and retrieves TODOs from localStorage.
         */
        var TodoStorage = (function () {
            function TodoStorage() {
                this.STORAGE_ID = 'todos-angularjs-typescript';
            }
            TodoStorage.prototype.get = function () {
                return JSON.parse(localStorage.getItem(this.STORAGE_ID) || '[]');
            };
            TodoStorage.prototype.put = function (todos) {
                localStorage.setItem(this.STORAGE_ID, JSON.stringify(todos));
            };
            return TodoStorage;
        })();
        storage.TodoStorage = TodoStorage;
    })(storage = _todos.storage || (_todos.storage = {}));
})(todos || (todos = {}));
var todos;
(function (todos) {
    var storage;
    (function (storage) {
        var StorageModule = (function () {
            function StorageModule() {
            }
            StorageModule.createStorage = function () {
                return new storage.TodoStorage();
            };
            return StorageModule;
        })();
        storage.StorageModule = StorageModule;
    })(storage = todos.storage || (todos.storage = {}));
})(todos || (todos = {}));
/*
 * Generated by Spaghetti 2.0 at 2014-11-07 15:02:50
 */
var todos;
(function (_todos) {
    var storage;
    (function (storage) {
        var __StorageModuleProxy = (function () {
            function __StorageModuleProxy() {
            }
            __StorageModuleProxy.prototype.createStorage = function () {
                return todos.storage.StorageModule.createStorage();
            };
            return __StorageModuleProxy;
        })();
        storage.__StorageModuleProxy = __StorageModuleProxy;
        function __createSpaghettiModule() {
            return new todos.storage.__StorageModuleProxy();
        }
        storage.__createSpaghettiModule = __createSpaghettiModule;
    })(storage = _todos.storage || (_todos.storage = {}));
})(todos || (todos = {}));
//# sourceMappingURL=storage.js.map
return todos.storage.__createSpaghettiModule(Spaghetti);

})

})(),"version":"unspecified","spaghettiVersion":"2.0"};});