/**
 * Layout module.
 */
module prezi.graphics.text.Layout {

	type AbstractText {
        void insert(int offset, String text)
        void delete(int offset, int end)
	}

    /**
     * Describes a block of text.
     */
    type Text extends AbstractText {
        /**
         * Inserts the given String at <code>offset</code>.
         */
        String getRawText()
        any getInternals()
    }

    Text createText()
}
