package com.prezi.spaghetti.haxe

import com.prezi.spaghetti.FQName

/**
 * Created by lptr on 19/11/13.
 */
final class HaxeUtils {
	public static File createHaxeSourceFile(FQName fqName, File outputDirectory, String contents) {
		return createHaxeSourceFile(fqName.localName, fqName, outputDirectory, contents)
	}

	public static File createHaxeSourceFile(String name, FQName baseName, File outputDirectory, String contents) {
		def packageDir = baseName.createNamespacePath(outputDirectory)
		packageDir.mkdirs()
		def file = new File(packageDir, name + ".hx")
		file.delete()
		file << "/*\n"
		file << " * Generated by Spaghetti.\n"
		file << " */\n"
		if (baseName.hasNamespace())
		{
			file << "package ${baseName.namespace};\n"
		}
		file << contents
		return file
	}
}
