class SpaghettiBundler
{
	static public function main()
	{
#if neko
		var args = Sys.args();
		if (args.length < 2)
		{
			printUsage();
			Sys.exit(1);
		}
		var type = args.shift();
		var call = switch (type)
		{
			case "module" :
				"define";
			case "application" :
				"require";
			default:
				throw "Bundle type should be either 'module' or 'application': ${type}";
		}
		var fileName = args.shift();
		var modules = [];
		for (module in args) {
			modules.push('"' + module + '"');
		}
		var haxe = sys.io.File.getContent(fileName);
		var prefix = '// Generated by Spaghetti
${call}([ ${modules.join(", ")} ], function() {
var __modules = arguments;
var __module;
';
		var suffix = 'return __module;
});
';
		sys.io.File.saveContent(fileName, prefix + haxe + suffix);
#end
	}

	static function printUsage()
	{
		Sys.println("usage: haxe --run SpaghttiBundler <module|application> <javascript-file> [<module-names>]");
	}
}
