class SpaghettiBundler
{
	static public function main()
	{
#if neko
		var args = Sys.args();
		if (args.length < 2)
		{
			printUsage();
			Sys.exit(1);
		}
		var type = args.shift();
		var call = switch (type)
		{
			case "module" :
				"define";
			case "application" :
				"require";
			default:
				throw "Bundle type should be either 'module' or 'application': ${type}";
		}
		var fileName = args.shift();
		var moduleFileNames = [];
		var modules = [];
		for (i in 0...args.length) {
			var module = args[i];
			moduleFileNames.push('"${module}"');
			modules.push('"${module}": arguments[${i}]');
		}

		var haxe = sys.io.File.getContent(fileName);
		var contents = '/* Generated by Spaghetti */ ${call}([ ${moduleFileNames.join(",")} ], function() { var __modules = { ${modules.join(",")} }; var __module; ${haxe}
return __module;
});
';
		sys.io.File.saveContent(fileName, contents);
#end
	}

	static function printUsage()
	{
		Sys.println("usage: haxe --run SpaghttiBundler <module|application> <javascript-file> [<module-names>]");
	}
}
