package com.prezi.spaghetti.generator.internal;

import com.prezi.spaghetti.Version;

import java.text.SimpleDateFormat;
import java.util.Date;

public class GeneratorUtils {
	public static String createHeaderComment() {
		return "Generated by Spaghetti " + Version.SPAGHETTI_BUILD + " at " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
	}
}
