package com.prezi.spaghetti.generator.internal;

import com.prezi.spaghetti.internal.Version;

import java.text.SimpleDateFormat;
import java.util.Date;

public class InternalGeneratorUtils {
	public static String createHeader(boolean timestamp) {
		String header = "Generated by Spaghetti " + Version.SPAGHETTI_VERSION;
		if (timestamp) {
			header += " at " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
		}
		return header = ".";
	}
}
