define(["require"],function(){var module=(function(dependencies){return function(init){return init.call({},(function(){var moduleUrl=dependencies[0]["toUrl"]("prezi.graphics.core.js");var baseUrl=moduleUrl.substr(0,moduleUrl.lastIndexOf("/"));return{getSpaghettiVersion:function(){return "2.0-rc6-SNAPSHOT";},getName:function(){return "prezi.graphics.core";},getVersion:function(){return "0.1";},getResourceUrl:function(resource){if(resource.substr(0,1)!="/"){resource="/"+resource;}return baseUrl+resource;},"dependencies":{"require":dependencies[0]}};})());};})(arguments);return{"module":module(function(Spaghetti) {
/*
 * Generated by Spaghetti 2.0-rc6-SNAPSHOT at 2014-09-14 01:18:21
 */
var prezi;
(function (prezi) {
	(function(graphics) {
		(function(core) {
			core.JsConst = {
				"alma": 1,
				"bela": "bela"
			};
		})(graphics.core || (graphics.core = {}));
		var core = graphics.core;
	})(prezi.graphics || (prezi.graphics = {}));
	var graphics = prezi.graphics;
})(prezi || (prezi = {}));
var prezi;
(function (prezi) {
	(function(graphics) {
		(function(core) {
			core.JsEnum = {
				"ALMA": 0,
				"BELA": 1
			};
		})(graphics.core || (graphics.core = {}));
		var core = graphics.core;
	})(prezi.graphics || (prezi.graphics = {}));
	var graphics = prezi.graphics;
})(prezi || (prezi = {}));
return {
	giveMeANumber: function() {
		return 41 + prezi.graphics.core.JsConst.alma;
	}
};

})
,"version":"0.1","spaghettiVersion":"2.0-rc6-SNAPSHOT"};});