/**
 * Text renderer module.
 */
module prezi.graphics.text.render {

	import prezi.graphics.core.JsEnum;
	import prezi.graphics.text.Text as Texty;

	interface Renderer {
		render(text: Texty): string;
	}

	createRenderer(prefix: string, suffix: string): Renderer;

	const Values {
		/**
		 * Some length
		 */
		MAX_LENGTH: int = 5;

		/**
		 * Some placeholder
		 */
		PLACEHOLDER: string = "string";
	}

	getResource(): string;
	getEnumValue(value: JsEnum): string;

}
