/**
 * Text renderer module.
 */
module prezi.graphics.text.render

import prezi.graphics.core.JsEnum
import prezi.graphics.text.Text as Texty

interface Renderer {
	string render(Texty text)
}

Renderer createRenderer(string prefix, string suffix)

const Values {
	/**
	 * Some length
	 */
	int MAX_LENGTH = 5

	/**
	 * Some placeholder
	 */
	string PLACEHOLDER = "string"
}

string getResource()
string getEnumValue(JsEnum value)
