package com.prezi.spaghetti;

import com.google.common.collect.Sets;
import com.prezi.spaghetti.ast.InterfaceNode;
import com.prezi.spaghetti.ast.InterfaceNodeBase;
import com.prezi.spaghetti.ast.InterfaceReferenceBase;
import com.prezi.spaghetti.ast.ReferableTypeNode;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;

public class GeneratorUtils {
	public static String createHeaderComment() {
		return "Generated by Spaghetti " + Version.SPAGHETTI_BUILD + " at " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
	}

	public static Set<InterfaceNodeBase> getAllInterfaces(InterfaceNode node) {
		Set<InterfaceNodeBase> allInterfaces = Sets.newLinkedHashSet();
		allInterfaces.add(node);
		addAllInterfaces(node, allInterfaces);
		return allInterfaces;
	}

	private static void addAllInterfaces(InterfaceNode node, Set<InterfaceNodeBase> allInterfaces) {
		for (InterfaceReferenceBase<?> superIfaceRef : node.getSuperInterfaces()) {
			InterfaceNodeBase superIface = superIfaceRef.getType();
			if (allInterfaces.add(superIface)) {
				if (superIface instanceof InterfaceNode) {
					addAllInterfaces((InterfaceNode) superIface, allInterfaces);
				}
			}
		}
	}
}
