package com.prezi.spaghetti;

import java.text.SimpleDateFormat;
import java.util.Date;

public class GeneratorUtils {
	public static String createHeaderComment() {
		return "Generated by Spaghetti at " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
	}
}
