module spaghetti.test as TestModule

import spaghetti.test.dependency.Fruit
import spaghetti.test.dependency.Prime
import spaghetti.test.dependency.Point2d

/**
 * This enum should be exported on the compiled module.
 */
enum Exported {
	Target = 42
	Another = 12
}

/**
 * Add the two numbers and return the result.
 */
int addTwoNumbers(int a, int b)

/**
 * Take the given enum value, and return the next value in the Fruit enum.
 * The enum is declared in the DependencyModule module.
 */
Fruit getNextEnumValue(Fruit value)

/**
 * Return the position for the first three primes.
 */
string getPositionInPrimes(Prime value)

const Numbers {
	ZERO = 0
	ONE = 1
	TWO = "two"
}

/**
 * Return the value of the constant "TWO" defined in right above Numbers.
 */
string getValueOfTwo()

struct Point3d extends Point2d {
	int z
}

/**
 * Create an instance of the Point3d type, and assign the parameters to its fields.
 */
Point3d createPoint3dWithGivenValues(int x, int y, int z)

/**
 * Return the Point2d created by DependencyModule.getPoint().
 */
Point2d getPointFromDependencyModule()

/**
 * Call DependencyModule.createStructViaCallback() with the given x and y values,
 * and return the Point2d created.
 */
Point2d getPointFromDependencyModuleViaCallback(int x, int y)

/**
 * Construct a new Point3d with the given values, and pass it to the callback.
 */
void returnPointViaCallback(int x, int y, int z, Point3d->void callback)

/**
 * Call into external dependency to get its version.
 */
string getExternalDependencyVersion()
