package com.prezi.spaghetti.typescript

import com.prezi.spaghetti.FQName

final class TypeScriptUtils {
	public static File createSourceFile(FQName fqName, File outputDirectory, String contents) {
		return sourceFile(fqName.localName, fqName, outputDirectory, contents, false)
	}

	public static File createSourceFile(String name, FQName baseName, File outputDirectory, String contents) {
		return sourceFile(name, baseName, outputDirectory, contents, false);
	}

	public static File createDeclarationSourceFile(FQName fqName, File outputDirectory, String contents) {
		return sourceFile(fqName.localName, fqName, outputDirectory, contents, true)
	}

	public static File sourceFile(String name, FQName baseName, File outputDirectory, String contents, boolean declarationOnly) {
		def file = new File(outputDirectory, name + ".ts")
		file.delete()
		file << "/*\n"
		file << " * Generated by Spaghetti.\n"
		file << " */\n"
		if (baseName.hasNamespace())
		{
			if (declarationOnly) {
				file << "declare module ${baseName.namespace} {\n"
			}
			else {
				file << "module ${baseName.namespace} {\n"
			}
			file << contents
			file << "}"
		}
		else {
			file << contents
		}
		return file
	}

	public static String capitalize(String name) {
		if (name == null || name == "") {
			return name
		}
		return name[0].toUpperCase() + name.substring(1)
	}
}
