package com.prezi.spaghetti.packaging

import com.prezi.spaghetti.Version

class CommonJsWrapperTest extends WrapperTestBase {
	def "CommonJS module"() {
		def originalScript = "/* Generated by Spaghetti */ function(Spaghetti){}"
		def result = new CommonJsWrapper().wrap(mockParams("com.example.test", "1.0", ["com.example.alma", "com.example.bela"], originalScript))

		expect:
		result == [
		        'module.exports=(function(){',
					'/* Generated by Spaghetti */ ',
					'return{',
						'"module":',
							'(',
								'function(Spaghetti){}\n',
							')',
							'.call({},(function(args){',
								'var baseUrl=__dirname;',
								'return{',
									'getSpaghettiVersion:function(){return "' + Version.SPAGHETTI_BUILD + '";},',
									'getName:function(){',
										'return "com.example.test";',
									'},',
									'getVersion:function(){return "1.0";},',
									'getResourceUrl:function(resource){',
										'if(resource.substr(0,1)!="/"){',
											'resource="/"+resource;',
										'}',
										'return baseUrl+resource;',
									'},',
									'"modules":{',
										'"com.example.alma":require("com.example.alma"),',
										'"com.example.bela":require("com.example.bela")',
									'}',
								'};',
							'})(arguments)),',
						'"version":"1.0",',
						'"spaghettiVersion":"' + Version.SPAGHETTI_BUILD + '"',
					'};',
				'})();'
		].join("")
	}

	def "CommonJS application"() {
		def dependencyTree = [
				"com.example.test": ["com.example.alma", "com.example.bela"].toSet(),
				"com.example.alma": ["com.example.bela"].toSet(),
				"com.example.bela": [].toSet()
		]
		def result = new CommonJsWrapper().makeApplication(dependencyTree, "com.example.test", true)

		expect:
		result == [
				'require("com.example.test")["module"]["main"]();\n',
		].join("")
	}
}
