package com.prezi.spaghetti.packaging

import com.prezi.spaghetti.generator.internal.InternalGeneratorUtils
import com.prezi.spaghetti.internal.Version
import com.prezi.spaghetti.packaging.internal.ExternalDependencyGenerator
import com.prezi.spaghetti.packaging.internal.SingleFileModuleWrapper

class SingleFileModuleWrapperTest extends WrapperTestBase {
	def "Single file module"() {
		def externalDependencies = ["React": "react", "\$": "jquery"]
		def originalScript = "/* Generated by Spaghetti */ return 3+4;"
		def result = new SingleFileModuleWrapper().wrap(mockParams("com.example.test", "1.0", ["com.example.alma", "com.example.bela"], externalDependencies, originalScript))

		expect:
		result == [
				'function(){',
					'var baseUrl=__dirname;',
		        	'return(function(){',
						'var $=arguments[0];',
						'var React=arguments[1];',
						'var Spaghetti={',
							'getSpaghettiVersion:function(){return "' + Version.SPAGHETTI_VERSION + '";},',
							'getModuleName:function(){',
								'return "com.example.test";',
							'},',
							'getModuleVersion:function(){return "1.0";},',
							'getResourceUrl:function(resource){',
								'if(resource.substr(0,1)!="/"){',
									'resource="/"+resource;',
								'}',
								'return baseUrl+resource;',
							'},',
							'"dependencies":{',
								'"com.example.alma":arguments[2],',
								'"com.example.bela":arguments[3]',
							'}',
						'};',
						'var module=function(f){return f(Spaghetti,$,React);};',
						'/* Generated by Spaghetti */ ',
						'return{',
							'"module":(function(){\n',
								'return 3+4;\n',
							'})(),',
							'"version":"1.0",',
							'"spaghettiVersion":"' + Version.SPAGHETTI_VERSION + '"',
						'};',
					'}).apply({},arguments);',
					'}'
		].join("")
	}

	def "Single file application"() {
		def dependencyTree = [
				"com.example.test": ["com.example.alma", "com.example.bela"].toSet(),
				"com.example.alma": ["com.example.bela"].toSet(),
				"com.example.bela": [].toSet()
		]
		def result = new SingleFileModuleWrapper().makeApplication(dependencyTree, "", "com.example.test", true, ["react": "react"])

		expect:
		result == [
				'var mainModule=modules["com.example.test"]["module"];',
				'mainModule["main"]();'
		].join("")
	}
}
