package com.prezi.spaghetti.packaging

class SingleFileWrapperTest extends WrapperTestBase {
	def "Single file module"() {
		def originalScript = "/* Generated by Spaghetti */ function(SpaghettiConfiguration){}"
		def result = new SingleFileWrapper().wrap(mockParams("com.example.test", "1.0", ["com.example.alma", "com.example.bela"], originalScript))

		expect:
		result == [
		        'function(){',
					'/* Generated by Spaghetti */ ',
					'return{',
						'"module":',
							'(',
								'function(SpaghettiConfiguration){}\n',
							')',
							'.call({},(function(args){',
								'var baseUrl=__dirname;',
								'return{',
									'"baseUrl":baseUrl,',
									'"modules":{',
										'"com.example.alma":args[0],',
										'"com.example.bela":args[1]',
									'},',
									'getName:function(){',
										'return "com.example.test";',
									'},',
									'getResourceUrl:function(resource){',
										'if(resource.substr(0,1)!="/"){',
											'resource="/"+resource;',
										'}',
										'return baseUrl+resource;',
									'}',
								'};',
							'})(arguments)),',
						'"version":"1.0"',
					'};',
				'}'
		].join("")
	}

	def "Single file application"() {
		def dependencyTree = [
				"com.example.test": ["com.example.alma", "com.example.bela"].toSet(),
				"com.example.alma": ["com.example.bela"].toSet(),
				"com.example.bela": [].toSet()
		]
		def result = new SingleFileWrapper().makeApplication("lajos", "mods", dependencyTree, "com.example.test", true)

		expect:
		result == [
				'modules["com.example.test"]["module"]["main"]();'
		].join("")
	}
}
