package com.prezi.spaghetti.packaging

import com.prezi.spaghetti.generator.internal.InternalGeneratorUtils
import com.prezi.spaghetti.internal.Version
import com.prezi.spaghetti.packaging.internal.ExternalDependencyGenerator
import com.prezi.spaghetti.packaging.internal.UmdModuleWrapper

class UmdModuleWrapperTest extends WrapperTestBase {
	def "UMD module"() {
		def externalDependencies = ["React": "react", "\$": "jquery", "example.test.name": "example.test.name"]
		def importedExternalDependencyVars = ExternalDependencyGenerator.getImportedVarNames(externalDependencies.keySet());
		def originalScript = "/* Generated by Spaghetti */ " + InternalGeneratorUtils.bundleJavaScript("", importedExternalDependencyVars)
		def result = new UmdModuleWrapper().wrap(mockParams("com.example.test", "1.0", ["com.example.alma", "com.example.bela"], ["com.example.croc"], externalDependencies, originalScript))

		expect:
		result == [
				';(function(){',
				'var baseUrl;',
				'var __factory=function(){',
					'var $=arguments[0];',
					'var React=arguments[1];',
					'var example=(example||{});',
					'example.test=(example.test||{});',
					'example.test.name=arguments[2];',
					'var module=(function(dependencies){',
						'return function(init){',
							'return init.call({},(function(){',
								'return{',
									'getSpaghettiVersion:function(){return "' + Version.SPAGHETTI_VERSION + '";},',
									'getModuleName:function(){',
										'return "com.example.test";',
									'},',
									'getModuleVersion:function(){return "1.0";},',
									'getResourceUrl:function(resource){',
										'if(resource.substr(0,1)!="/"){',
											'resource="/"+resource;',
										'}',
										'return baseUrl+resource;',
									'},',
									'"dependencies":{',
										'"com.example.alma":dependencies[3],',
										'"com.example.bela":dependencies[4],',
										'"com.example.croc":dependencies[5]',
									'}',
								'};',
							'})(),$,React,example);',
						'};',
					'})(arguments);',
					'/* Generated by Spaghetti */ ',
					'var moduleImpl=(function(){return module(function(Spaghetti,$,React,example) {\n\n})\n\n})() || {};\n',
					'moduleImpl["module"]=moduleImpl;\n',
					'return moduleImpl;',
				'};',
				'if(typeof define==="function"&&define.amd){',
					'define("com.example.test",["require","jquery","react","example.test.name","com.example.alma","com.example.bela"],function(){',
						'var moduleUrl=arguments[0]["toUrl"]("com.example.test.js");',
						'baseUrl=moduleUrl.substr(0,moduleUrl.lastIndexOf("/"));',
						'return(__factory).apply({},[].slice.call(arguments,1).concat([function(){return new Promise(function(resolve,reject){require(["com.example.croc"],function(m){resolve(m.lazyModule);},function(err){reject(err);});});}]));',
					'});',
				'}else if(typeof exports==="object"&&typeof exports.nodeName!=="string"){',
					'baseUrl=__dirname;',
					'module.exports=(__factory)(require("jquery"),require("react"),require("example.test.name"),require("com.example.alma"),require("com.example.bela"),function(){return Promise.resolve(require("com.example.croc").lazyModule);});',
				'}else{',
					'this["com.example.test"]=__factory($,React,example.test.name,this["com.example.alma"],this["com.example.bela"],function(){return Promise.resolve(this["com.example.croc"].lazyModule);});',
				'}',
				'}).call(this);'
		].join("")
	}

	def "UMD application"() {
		def dependencyTree = [
				"com.example.test": ["com.example.alma", "com.example.bela"].toSet(),
				"com.example.alma": ["com.example.bela"].toSet(),
				"com.example.bela": [].toSet()
		]
		def externals = [
				"react": "react"
		]
		def result = new UmdModuleWrapper().makeApplication(dependencyTree, "modules", "com.example.test", true, externals)

		expect:
		result == [
				'if(typeof define==="function"&&define.amd){',
					'require["config"]({',
						'"baseUrl":".",',
						'"paths":{',
							'"com.example.alma":"modules/com.example.alma/com.example.alma",',
							'"com.example.bela":"modules/com.example.bela/com.example.bela",',
							'"com.example.test":"modules/com.example.test/com.example.test",',
							'"react":"react"',
						'}',
					'});',
				'}',
				'if(typeof define==="function"&&define.amd){',
					'require(["com.example.test"],function(__mainModule){',
						'__mainModule["main"]();',
					'});',
				'}else if(typeof exports==="object"&&typeof exports.nodeName!=="string"){',
					'require("com.example.test")["main"]();',
				'}else{',
					'this["com.example.test"]["main"]();',
				'}',
				'\n'
		].join("")
	}
}
